[package]
name = "xmlparser"
version = "0.13.2"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
categories = ["parser-implementations"]
description = "Pull-based, zero-allocation XML parser."
documentation = "https://docs.rs/xmlparser/"
keywords = ["xml", "parser", "tokenizer"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/RazrFalcon/xmlparser"
edition = "2018"

[badges]
travis-ci = { repository = "RazrFalcon/xmlparser" }

[features]
default = ["std"]
std = []
